version:           '2'
services:

  app_environment:
    image: base:php7_developer
    stdin_open:    true
    tty:           true
    env_file: .env
    build:
      context: ./docker/base_php7_developer
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    #
    # INTERNAL NETWORKING
    #
    links:
      - database_sql
      - database_couch
      - message_rabbitmq
      - mail_server
    #
    # SHARED HOST VOLUMES
    #
    volumes:
      # Log location
      - ./docker/log/base_symfony_php7:/srv/app/logs
      # Extra platform Configuration
      - ./docker/base_php7/php-overrides.ini:/etc/php7/conf.d/overrides.ini
      # Project files
      - /path/to/home/development/pivot88/site:/srv
      - /path/to/home/development/pivot88/developer_version_info.json:/srv/version_info.json
      #
      #  --- REQUIRED CHANGES BELOW ---
      #
      #  - VCS Access
      #  Set the first parameter to a path on your system with an SSH config and
      #  the keys to access the reopositories being used
      - /path/to/home/.ssh:/php/.ssh

  app_platform:
    build:
      context:       ./docker/platform_php7
    image:         platform:php7
    volumes_from:
      - app_environment
    #
    # INTERNAL NETWORKING
    #
    links:
      - database_sql
      - database_couch
      - message_rabbitmq
      - mail_server
    #
    # SHARED HOST VOLUMES
    #
    volumes:
      # Extra platform Configuration
      - ./docker/platform_php7/pool_config.conf:/etc/php7/php-fpm.d/www.conf
      - ./docker/log/platform_php7:/var/log/php7

  # Fake SMTP service
  mail_server:
    image: mailhog/mailhog
    ports:
      - 82:8025

  # Log grabber
  # log_elk:
  #    image: sebp/elk:550
  #    ports:
  #     - 81:80
  #    volumes:
  #     - ./docker/elk/logstash:/etc/logstash
  #     - ./docker/elk/logstash/patterns:/opt/logstash/patterns
  #     - ./docker/log:/internal_logs